# Generated by Django 4.2.1 on 2023-05-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='name',
            new_name='nnom',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='price',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='vegan',
            new_name='vegetarienne',
        ),
    ]
